{
 "title": ".NET runtime metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "dotnet_build_info" }
  ]
 },
 "panels": [
  { "title": "Current Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% CPU consumption",
   "type": "singlestat",
   "description": "The percentage of available CPU resources consumed.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__interval]) / process_cpu_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% Paused time",
   "type": "singlestat",
   "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% GC CPU consumption",
   "type": "singlestat",
   "description": "The percentage of total process CPU utilization that was dedicated to performing garbage collections.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% JIT CPU consumption",
   "type": "singlestat",
   "description": "The percentage of CPU utilization that was dedicated to compiling methods by the Just In Time (JIT) compiler.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Thread pool scheduling latency",
   "type": "singlestat",
   "description": "The delay between when a job is scheduled for execution on the thread pool and when it starts execution. Measurement taken from the 90th percentile.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_scheduling_delay_seconds_sum{instance=\"$instance\"}[$__interval])) / sum(rate(dotnet_threadpool_scheduling_delay_seconds_count{instance=\"$instance\"}[$__interval]))"
    }
   ]
  },
  { "title": "Memory / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "dotnet_gc_heap_size_bytes{instance=\"$instance\"}",
     "legendFormat": "gen {{gc_generation}}"
    }
   ]
  },
  {
   "title": "Bytes allocated (by heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{gc_heap=\"loh\", instance=\"$instance\"}[$__interval])) by (gc_heap)",
     "legendFormat": "Large object heap (objects > 85KB)"
    },
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{gc_heap=\"soh\", instance=\"$instance\"}[$__interval])) by (gc_heap)",
     "legendFormat": "Small object heap"
    }
   ]
  },
  {
   "title": "GC CPU + pause ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\"}",
     "legendFormat": "GC CPU %"
    },
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}",
     "legendFormat": "GC Pause %"
    }
   ]
  },
  {
   "title": "Number of GC collections/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_collection_seconds_count{instance=\"$instance\"}[$__interval])) by (gc_generation, gc_type)",
     "legendFormat": "gen {{gc_generation}}: {{gc_type}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average GC duration (by generation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_sum{instance=\"$instance\"}[$__interval])) by (gc_generation) / sum(increase(dotnet_gc_collection_seconds_count{instance=\"$instance\"}[$__interval])) by (gc_generation) ",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  { "title": "Thread pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Thread pool scheduling latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (le) (increase(dotnet_threadpool_scheduling_delay_seconds_bucket{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Num thread pool threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_threadpool_num_threads{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Thread pool adjustment reasons",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_adjustments_total{instance=\"$instance\"}[$__interval])) by (adjustment_reason )",
     "legendFormat": "{{adjustment_reason}}"
    }
   ]
  },
  { "title": "JIT compliation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Methods compiled/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_jit_method_total{dynamic=\"true\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Dynamic methods"
    },
    {
     "expr": "rate(dotnet_jit_method_total{dynamic=\"false\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Methods"
    }
   ]
  },
  {
   "title": "JIT CPU usage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dotnet_jit_cpu_ratio{instance=\"$instance\"}",
     "legendFormat": "% CPU utilization"
    }
   ]
  },
  { "title": "Contention", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Locks contended/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_contention_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "# Locks contended"
    }
   ]
  },
  {
   "title": "Time waiting for locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_contention_seconds_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Waiting time"
    }
   ]
  }
 ]
}