name: run-tests

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    # excluding When_IO_work_is_executed_on_the_thread_pool_then_the_number_of_io_threads_is_measured for now, for some reason we don't seem to be
    # generating IO thread events in the github actions environment
    - run: dotnet test -c "Debug" --filter Name!=When_IO_work_is_executed_on_the_thread_pool_then_the_number_of_io_threads_is_measured
